const fs=require('fs'), crypto=require('crypto'), path=require('path');
const root=process.cwd(), out=path.join(root,'data/liuyao_knowledge/stage5-final-review-v1'), auditDir='/Users/chenxiaohe/Documents/ChatGPT/final project/卦例候选审核';
const read=p=>fs.readFileSync(p,'utf8').trim().split('\n').filter(Boolean).map(JSON.parse), write=(f,a)=>fs.writeFileSync(path.join(out,f),a.map(JSON.stringify).join('\n')+'\n');
fs.mkdirSync(out,{recursive:true});
const candidates=read('data/liuyao_knowledge/stage2-v1/cases.jsonl'), review=read(auditDir+'/审核明细.jsonl'), rules=read('data/liuyao_knowledge/stage3-v1/rules.jsonl'), passages=read('data/liuyao_knowledge/stage2-v1/passages.jsonl');
const pById=new Map(passages.map(x=>[x.passage_id,x])), rByNo=new Map(review.map(x=>[x.review_no,x]));
const special=new Set([24,35,64,67,116,117,140,164,189,201]);
const sha=s=>crypto.createHash('sha256').update(s).digest('hex');
const spans=(r,start,end)=>passages.filter(p=>p.source_id===r.source_id&&p.start>=start&&p.end<=end).map(p=>p.passage_id);
const fields=t=>({question_status:/占|問|问/.test(t)?'present':'missing',chart_status:/⚊|⚋|○|ㄨ/.test(t)?'present':'missing',judgment_status:/斷曰|断曰|予曰/.test(t)?'present':'missing',outcome_status:/果于|果在|後果|后果/.test(t)?'present':'missing'});
const entities=[], mapping=[], dispositions=[];
function addEntity(r,c,idx,text,start,end,kind='specific_case'){end=Math.min(end,r.end);let id='final-case:'+String(r.review_no).padStart(3,'0')+'-'+idx, group='case-group:'+String(r.review_no).padStart(3,'0'), reading='reading:'+String(r.review_no).padStart(3,'0')+'-'+idx;let pass=spans(r,start,end), f=fields(text);entities.push({final_case_id:id,case_group_id:group,reading_id:reading,entity_kind:kind,source_id:r.source_id,source_revision_id:r.source_revision_id,source_title:r.source_title,start,end,passage_ids:pass,original_text:text,...f,remaining_issues:r.flags,review_status:'reviewed_manual_boundary',retrieval_eligible:f.chart_status==='present'&&f.question_status==='present'&&f.judgment_status==='present'&&f.outcome_status==='present',production_eligible:false});mapping.push({original_review_no:r.review_no,original_case_id:r.case_id,disposition:'mapped_to_final_case',final_case_id:id,case_group_id:group,reading_id:reading,start,end});}
for(const r of review){const c=candidates.find(x=>x.case_id===r.case_id); if(!c)throw Error('missing '+r.review_no); if(['通用论述','教学示例','章节或规则','混排待核对','前例续文'].includes(r.category_suggestion)){dispositions.push({original_review_no:r.review_no,original_case_id:r.case_id,category:r.category_suggestion,action:r.suggested_action,source_id:r.source_id,start:r.start,end:r.end,original_text:r.raw_text,retrieval_eligible:false});mapping.push({original_review_no:r.review_no,original_case_id:r.case_id,disposition:'diverted_noncase',target_category:r.category_suggestion});continue} if(special.has(r.review_no))continue; addEntity(r,c,1,r.raw_text,r.start,r.end);}
function split(r,marks){let cuts=marks.map(m=>r.raw_text.indexOf(m)).filter(x=>x>=0).sort((a,b)=>a-b);cuts.forEach((s,i)=>{let e=i+1<cuts.length?cuts[i+1]:r.raw_text.length, t=r.raw_text.slice(s,e).trim(); if(t) addEntity(r,null,i+1,t,r.start+s,r.start+e)});}
for(const n of [...special]){let r=rByNo.get(n); if(n===24)split(r,['又如酉月乙未日','又有巳月甲寅日','如申月己卯日']);else if(n===35)split(r,['如卯月壬辰日','又酉月丙辰日']);else if(n===64){let e=r.raw_text.indexOf('《星煞章》');addEntity(r,null,1,r.raw_text.slice(0,e).trim(),r.start,r.start+e);dispositions.push({original_review_no:n,original_case_id:r.case_id,category:'章节或规则',action:'从星煞章起分流',source_id:r.source_id,start:r.start+e,end:r.end,original_text:r.raw_text.slice(e),retrieval_eligible:false});}
else if(n===67)split(r,['如卯月辛巳','如未月庚寅日','卽如丑月壬子日']);else if(n===116)split(r,['如酉月癸未日','如巳月丙申日']);else if(n===117)split(r,['如酉月初五','辰日癸巳日','酉日丙子日']);else if(n===140){let e=r.raw_text.indexOf('克在內');addEntity(r,null,1,r.raw_text.slice(0,e).trim(),r.start,r.start+e);dispositions.push({original_review_no:n,original_case_id:r.case_id,category:'通用规则论述',action:'前三次防患连续占问保留同一 reading；后文分流',source_id:r.source_id,start:r.start+e,end:r.end,original_text:r.raw_text.slice(e),retrieval_eligible:false});}
else if(n===164){let e=r.raw_text.indexOf('父旺官衰');addEntity(r,null,1,r.raw_text.slice(0,e).trim(),r.start,r.start+e);dispositions.push({original_review_no:n,original_case_id:r.case_id,category:'通用规则论述',action:'乡试连续两卦保留同一 reading；后文分流',source_id:r.source_id,start:r.start+e,end:r.end,original_text:r.raw_text.slice(e),retrieval_eligible:false});}
else if(n===189)split(r,['如巳月己亥日','曾于巳月丁卯日']);else if(n===201)split(r,['又如一日時值初更','一日到一府中']);}
// Rules: evidence must resolve to a passage; proposals remain non-executable and conflicts remain explicit.
const audited=rules.map(x=>{const evidence=x.source_passage_ids.map(id=>pById.get(id)).filter(Boolean);let blocked=evidence.length!==x.source_passage_ids.length;let conflict=x.conflict_group_ids.length>0;return {...x,revision:x.revision+1,review_status:blocked?'blocked':'modified_pass',status:blocked?'blocked':'reviewed',reviewer:'stage5-final-review',review_evidence_passage_ids:evidence.map(e=>e.passage_id),evidence_audit:evidence.map(e=>({passage_id:e.passage_id,start:e.start,end:e.end,excerpt:e.text.slice(0,180)})),audit_reason:blocked?'来源 passage 缺失，不能确认。':(conflict?'原文证据存在，但与冲突组并存；保留分支，不可自动裁决。':'原文 passage、范围与规则主题可回链；该规则仍只是工程提案。'),change_record:'补充逐条证据回链与审核状态；未将任何文字规则编码为可执行条件。',production_eligible:false,executable:false};});
write('final_cases.jsonl',entities);write('candidate_entity_mapping.jsonl',mapping);write('diverted_material.jsonl',dispositions);write('rules.jsonl',audited);
const coverage=new Set(mapping.map(x=>x.original_review_no));
const errors=[]; if(new Set(entities.map(x=>x.final_case_id)).size!==entities.length)errors.push('duplicate final_case_id'); if(coverage.size!==253)errors.push('original review coverage '+coverage.size+'/253'); if(entities.some(x=>x.start>=x.end))errors.push('invalid spans'); if(audited.some(x=>x.review_evidence_passage_ids.length===0))errors.push('rule no evidence');
const report={generated_at:new Date().toISOString(),input_candidate_count:253,original_candidate_coverage_count:coverage.size,final_case_count:entities.length,diverted_count:dispositions.length,mapping_row_count:mapping.length,rule_count:audited.length,rule_status_counts:audited.reduce((a,x)=>(a[x.review_status]=(a[x.review_status]||0)+1,a),{}),validation_errors:errors,release_status:'review_only_no_index_or_production_retrieval',source_snapshots:{stage2:'data/liuyao_knowledge/stage2-v1',stage3:'data/liuyao_knowledge/stage3-v1',audit:auditDir}};
fs.writeFileSync(path.join(out,'validation_report.json'),JSON.stringify(report,null,2));fs.writeFileSync(path.join(out,'manifest.json'),JSON.stringify({...report,files:['final_cases.jsonl','candidate_entity_mapping.jsonl','diverted_material.jsonl','rules.jsonl','validation_report.json']},null,2));
const md=['# 最终案例与规则审核报告','','本版本是只读审核派生层，不覆盖 stage2/stage3，不重建索引，不启用生产检索。','',`- 原候选：253；映射覆盖：${mapping.length}` ,`- 最终案例实体：${entities.length}` ,`- 分流材料：${dispositions.length}` ,`- 规则：${audited.length}（modified_pass ${audited.filter(x=>x.review_status==='modified_pass').length}；blocked ${audited.filter(x=>x.review_status==='blocked').length}）`,'','## 已落实的人工确认','', '024 拆三例；035 拆两例；064 截至星煞章前；067 分出首例、后例与规则；116 拆两例；117 拆三组连续天气占问；140 三次防患合为一 reading；164 两卦乡试合为一 reading；189 拆两例；201 拆同病患连续占验与人参新案。','', '## 规则限制','','规则文本审核通过不表示已编码或发布；全部 `executable=false`、`production_eligible=false`。带冲突组的规则保持分支，不强行消解。','', '详见同目录 JSONL 与 validation_report.json。',''].join('\n');fs.writeFileSync(path.join(out,'FINAL_REPORT.md'),md);
fs.writeFileSync(path.join(auditDir,'最终案例与规则审核报告.md'),md);
const ruleMd=['# 六爻规则逐条审核','','本表审核的是文本来源、分类、关系/条件/动作/例外、观点归属与冲突声明；不是领域认证或可执行规则发布。','','| 规则 | 类别 | 审核结论 | 来源证据 | 分歧/限制 |','|---|---|---|---|---|',...audited.map(x=>`| ${x.rule_id} | ${x.rule_type} | ${x.review_status} | ${x.review_evidence_passage_ids.join('<br>')} | ${x.conflict_group_ids.length?'保留冲突组：'+x.conflict_group_ids.join(','):'工程提案；不可执行'} |`),'','所有规则：`executable=false`、`production_eligible=false`。`modified_pass` 仅表示可回链的文字审核完成；不表示条件已编码或可用于生产。',''].join('\n');
fs.writeFileSync(path.join(out,'RULE_AUDIT.md'),ruleMd);fs.writeFileSync(path.join(auditDir,'六爻规则逐条审核.md'),ruleMd);
if(errors.length)process.exitCode=1;
